apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: k8s-ai-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
